export const INITIALIZATION = "INITIALIZATION";
export const DATA_PROCESSING = "DATA_PROCESSING";
export const HANDLE_SERVER_ERROR = "HANDLE_SERVER_ERROR";
export const HANDLE_CLIENT_ERROR = "HANDLE_CLIENT_ERROR";
export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
